custom_css: ['/assets/css/custom.css']

title: David Mould - GitHub Blog

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  My blog for University coursework - Creative Technologies Professionalism, however I may keep the blog up to date as a portfolio!

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

title: David Mould Blog
author: David Mould

# Theme-specific settings
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/FEDavid" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/david-mould-0418b856/" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/8387861/david-mould" }
    
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
  - coursework.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
