title: David Mould - GitHub Blog
author:
  name: David Mould
  email: "chromedm@live.co.uk"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/FEDavid" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/david-mould-0418b856/" }
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
