theme: minima
minima:
  skin: dark
  social_links:
  - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
  - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
author:
  name: David Mould
  email: "john.smith@foobar.com"
